version: '3'
services:
  redmine:
    container_name: redmine
    restart: always
    image: getjv/redmine
    ports:
      - "8080:3000"
    environment:
      - REDMINE_DB_POSTGRES=postgres
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=secret
    links:
      - postgres
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=redmine


     
     